-- Run this once in the Supabase SQL Editor (Dashboard → SQL Editor → New query).
-- It creates a single key-value table that mirrors the storage interface the
-- app already uses, scoped per signed-in user via Row Level Security — so
-- even though the anon key is public in the client bundle, each user can only
-- ever read or write their own rows.

create table if not exists public.kv_store (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  key text not null,
  value text not null,
  shared boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (user_id, key, shared)
);

alter table public.kv_store enable row level security;

create policy "individuals manage their own rows"
  on public.kv_store
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
